### ISSUE TITLE
BUG - Stamina não carrega!

### ISSUE THREAD

**Issue by Amorim5095** [FelipeVieiraVendramini/World-Conquer-Online#27]
Em alguns accs a stamina do conquer nunca carrega!

**Comment by Amorim5095** [comment]
Acontece com os novos accs, simplesmente a estamina nunca enche.

**Comment by FelipeVieiraVendramini** [comment]
Criei duas contas novas por aqui e ambas foram normalmente. Um Taoista e um Trojan.
