### ISSUE TITLE
BUG - ERRO AO DONATAR CPS

### ISSUE THREAD

**Issue by Amorim5095** [FelipeVieiraVendramini/World-Conquer-Online#29]
Players estão donatando 9 kkk no rank e esta sumindo sempre 200 k de cps sem contar nada no rank!

**Comment by FelipeVieiraVendramini** [comment]
Não é um bug e eu particularmente nem me responsabilizaria pelo problema, mas vou adicionar o limite. O 3.0 tem isso até hoje. O limite é de dois bilhões por vez e nunca foi nenhum segredo.
