### ISSUE TITLE
BUG - CAP DO NINJA SUMIU DA BAG DO PLAYER AO COLOCAR +8 E RELOGAR!

### ISSUE THREAD

**Issue by Amorim5095** [FelipeVieiraVendramini/World-Conquer-Online#31]
BUG - CAP DO NINJA SUMIU DA BAG DO PLAYER AO COLOCAR +8 E RELOGAR!

**Comment by FelipeVieiraVendramini** [comment]
Problema com o itemtype que é do servidor 5692. Provavelmente tentaram upar além do limite e o servidor aceitou, próxima manutenção hoje corrige.
