### ISSUE TITLE
BUG - Revive here não esta funcionando!

### ISSUE THREAD

**Issue by Amorim5095** [FelipeVieiraVendramini/World-Conquer-Online#32]
BUG, REV HERE não está funcionando!

**Comment by FelipeVieiraVendramini** [comment]
Não está funcionando aonde? Pq se você testou em TwinCity ele não funciona mesmo.
Vou investigar.

**Comment by FelipeVieiraVendramini** [comment]
Corrigido, falha minha mesmo.
